server:
  port: 9001

spring :
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=microservices
    username: sa
    password: password
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
  zipkin:
    enabled: true
    service.name: DEPARTMENT-SERVICE
    sender.type: web
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0